---
slug: :user_detail_view
depends:
  mikutter: '5.0'
  plugin:
  - gui
  - gtk3
  - command
  - uitranslator
  - intent
  - skin
  - twitter
version: '2.0'
author: toshi_a
name: プロフィール
description: 特定のユーザのプロフィールを表示する機能を追加する。また、プロフィール画面をカスタマイズするためのAPIを提供する
